Repository notvalproate/riffly, pull requests merged in 2024-06, with the labels that each got.

#18 Dynamoose Setup!
  server/.env.example
  server/database/dynamo.js
  server/models/user.model.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/utils/environment.js
Labels: enhancement

#20 Old Lyrics Fix
  client/src/app/home/home-components/song-player/song-player.component.ts
  server/controllers/lyrics/lyricsApi.js
Labels: bug

#21 Added /me/top/genres Endpoint
  server/controllers/spotify/spotifyApi.js
  server/routes/top.js
Labels: enhancement, question

#22 User model has been added!
  server/controllers/spotify/spotifyApi.js
  server/models/user.model.js
Labels: enhancement

#23 Create User On Login
  server/controllers/general/friends.controller.js
  server/controllers/spotify/spotifyApi.js
  server/controllers/spotify/spotifyAuth.js
  server/middleware/error.handler.js
  server/models/user.model.js
  server/package-lock.json
  server/package.json
  server/routes/friends.js
  server/routes/me.js
  server/server.js
  server/utils/spotify.parser.js
Labels: enhancement

#24 Merging Second Sprint
  client/src/app/auth/auth.component.ts
  client/src/app/charts/charts.component.ts
  client/src/app/home/home-components/lyrics-display/lyrics-display.component.html
  client/src/app/home/home-components/lyrics-display/lyrics-display.component.scss
  client/src/app/home/home-components/lyrics-display/lyrics-display.component.spec.ts
  client/src/app/home/home-components/lyrics-display/lyrics-display.component.ts
  client/src/app/home/home-components/progress-tracker/progress-tracker.component.html
  client/src/app/home/home-components/progress-tracker/progress-tracker.component.scss
  client/src/app/home/home-components/progress-tracker/progress-tracker.component.spec.ts
  client/src/app/home/home-components/progress-tracker/progress-tracker.component.ts
  client/src/app/home/home-components/song-card/song-card.component.html
  client/src/app/home/home-components/song-card/song-card.component.scss
  client/src/app/home/home-components/song-card/song-card.component.spec.ts
  client/src/app/home/home-components/song-card/song-card.component.ts
  client/src/app/home/home-components/song-player/song-player.component.html
  client/src/app/home/home-components/song-player/song-player.component.scss
  client/src/app/home/home-components/song-player/song-player.component.spec.ts
  client/src/app/home/home-components/song-player/song-player.component.ts
  client/src/app/home/home.component.html
  client/src/app/home/home.component.scss
  client/src/app/home/home.component.ts
  client/src/app/interfaces/LyricsData.ts
  client/src/app/interfaces/ProgressData.ts
  client/src/app/interfaces/SongCardData.ts
  client/src/app/login/login.component.ts
  client/src/app/services/auth.service.ts
  client/tsconfig.json
  node_modules/.package-lock.json
  node_modules/express-async-handler/.travis.yml
  node_modules/express-async-handler/README.md
  node_modules/express-async-handler/index.d.ts
  node_modules/express-async-handler/index.js
  node_modules/express-async-handler/package.json
  node_modules/express-async-handler/test.js
  server/.env.example
  server/controllers/general/friends.controller.js
  server/controllers/lyrics/geniusApi.js
  server/controllers/lyrics/lyricsApi.js
  server/controllers/lyrics/musixmatchApi.js
  server/controllers/spotify/spotifyApi.js
  server/controllers/spotify/spotifyAuth.js
  server/database/cacher.js
  server/database/dynamo.js
  server/middleware/error.handler.js
  server/models/user.model.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/friends.js
  server/routes/me.js
  server/routes/top.js
  server/routes/track.js
  server/server.js
  server/utils/api.error.js
  server/utils/environment.js
  server/utils/spotify.parser.js
Labels: enhancement

#25 Friend Endpoints Finished!
  server/controllers/general/friends.controller.js
  server/routes/friends.js
Labels: enhancement

#26 Added friend service to interact with friends endpoint
  client/src/app/services/friend.service.spec.ts
  client/src/app/services/friend.service.ts
Labels: enhancement

#27 friend side bar made
  client/src/app/general/friend-sidebar/friend-sidebar.component.html
  client/src/app/general/friend-sidebar/friend-sidebar.component.scss
  client/src/app/general/friend-sidebar/friend-sidebar.component.spec.ts
  client/src/app/general/friend-sidebar/friend-sidebar.component.ts
  client/src/app/home/home.component.html
  client/src/app/home/home.component.scss
  client/src/app/home/home.component.ts
Labels: enhancement

#28 Added the colors to _colors partial
  client/src/app/app.component.ts
  client/src/app/app.config.ts
  client/src/app/app.routes.ts
  client/src/app/general/friend-sidebar/services/friend.service.spec.ts
  client/src/app/general/friend-sidebar/services/friend.service.ts
  client/src/app/pages/auth/auth.component.html
  client/src/app/pages/auth/auth.component.scss
  client/src/app/pages/auth/auth.component.ts
  client/src/app/pages/charts/charts.component.html
  client/src/app/pages/charts/charts.component.scss
  client/src/app/pages/charts/charts.component.spec.ts
  client/src/app/pages/charts/charts.component.ts
  client/src/app/pages/charts/services/user-charts.service.spec.ts
  client/src/app/pages/charts/services/user-charts.service.ts
  client/src/app/pages/home/home.component.html
  client/src/app/pages/home/home.component.scss
  client/src/app/pages/home/home.component.ts
  client/src/app/pages/home/song-player/lyrics-display/lyrics-display.component.html
  client/src/app/pages/home/song-player/lyrics-display/lyrics-display.component.scss
  client/src/app/pages/home/song-player/lyrics-display/lyrics-display.component.spec.ts
  client/src/app/pages/home/song-player/lyrics-display/lyrics-display.component.ts
  client/src/app/pages/home/song-player/progress-tracker/progress-tracker.component.html
  client/src/app/pages/home/song-player/progress-tracker/progress-tracker.component.scss
  client/src/app/pages/home/song-player/progress-tracker/progress-tracker.component.spec.ts
  client/src/app/pages/home/song-player/progress-tracker/progress-tracker.component.ts
  client/src/app/pages/home/song-player/song-card/song-card.component.html
  client/src/app/pages/home/song-player/song-card/song-card.component.scss
  client/src/app/pages/home/song-player/song-card/song-card.component.spec.ts
  client/src/app/pages/home/song-player/song-card/song-card.component.ts
  client/src/app/pages/home/song-player/song-player.component.html
  client/src/app/pages/home/song-player/song-player.component.scss
  client/src/app/pages/home/song-player/song-player.component.spec.ts
  client/src/app/pages/home/song-player/song-player.component.ts
  client/src/app/pages/login/login.component.html
  client/src/app/pages/login/login.component.scss
  client/src/app/pages/login/login.component.ts
  client/src/app/styles/_colors.scss
  client/src/shared/guards/auth.guard.spec.ts
  client/src/shared/guards/auth.guard.ts
  client/src/shared/guards/authpage.guard.spec.ts
  client/src/shared/guards/authpage.guard.ts
  client/src/shared/interfaces/LyricsData.ts
  client/src/shared/interfaces/ProgressData.ts
  client/src/shared/interfaces/SongCardData.ts
  client/src/shared/services/api.service.spec.ts
  client/src/shared/services/api.service.ts
  client/src/shared/services/auth.service.spec.ts
  client/src/shared/services/auth.service.ts
  client/src/shared/services/polling.service.spec.ts
  client/src/shared/services/polling.service.ts
  client/src/shared/services/user-info.service.spec.ts
  client/src/shared/services/user-info.service.ts
Labels: enhancement

#29 Sidebar Profile
  client/package-lock.json
  client/package.json
  client/src/app/general/friend-sidebar/friend-sidebar.component.html
  client/src/app/general/friend-sidebar/friend-sidebar.component.ts
  client/src/app/general/friend-sidebar/profile/profile.component.html
  client/src/app/general/friend-sidebar/profile/profile.component.scss
  client/src/app/general/friend-sidebar/profile/profile.component.spec.ts
  client/src/app/general/friend-sidebar/profile/profile.component.ts
  client/src/app/pages/home/home.component.html
  client/src/app/pages/home/home.component.ts
  client/src/app/pages/home/song-player/song-card/song-card.component.scss
  client/src/app/styles/_colors.scss
  client/src/assets/.gitkeep
  client/src/assets/mei.jpg
Labels: enhancement

#30 Friend Request Component Added
  client/src/app/general/friend-sidebar/add-friend/add-friend.component.html
  client/src/app/general/friend-sidebar/add-friend/add-friend.component.scss
  client/src/app/general/friend-sidebar/add-friend/add-friend.component.spec.ts
  client/src/app/general/friend-sidebar/add-friend/add-friend.component.ts
  client/src/app/general/friend-sidebar/friend-sidebar.component.html
  client/src/app/general/friend-sidebar/friend-sidebar.component.ts
  client/src/app/general/friend-sidebar/services/friend.service.ts
  client/src/app/pages/home/song-player/song-card/song-card.component.html
  server/controllers/general/friends.controller.js
Labels: enhancement

#31 Refresh Token Implemented!
  client/src/app/app.config.ts
  client/src/app/general/friend-sidebar/profile/profile.component.ts
  client/src/environments/environment.development.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
  client/src/shared/interceptors/auth.interceptor.spec.ts
  client/src/shared/interceptors/auth.interceptor.ts
  client/src/shared/interceptors/header.interceptor.spec.ts
  client/src/shared/interceptors/header.interceptor.ts
  client/src/shared/services/auth.service.ts
Labels: enhancement

#33 Friend list
  client/src/app/app.component.html
  client/src/app/app.component.ts
  client/src/app/general/friend-sidebar/add-friend/add-friend.component.html
  client/src/app/general/friend-sidebar/add-friend/add-friend.component.scss
  client/src/app/general/friend-sidebar/friend-list/friend-list.component.html
  client/src/app/general/friend-sidebar/friend-list/friend-list.component.scss
  client/src/app/general/friend-sidebar/friend-list/friend-list.component.spec.ts
  client/src/app/general/friend-sidebar/friend-list/friend-list.component.ts
  client/src/app/general/friend-sidebar/friend-list/names-list/names-list.component.html
  client/src/app/general/friend-sidebar/friend-list/names-list/names-list.component.scss
  client/src/app/general/friend-sidebar/friend-list/names-list/names-list.component.spec.ts
  client/src/app/general/friend-sidebar/friend-list/names-list/names-list.component.ts
  client/src/app/general/friend-sidebar/friend-sidebar.component.html
  client/src/app/general/friend-sidebar/friend-sidebar.component.scss
  client/src/app/general/friend-sidebar/friend-sidebar.component.ts
  client/src/app/general/friend-sidebar/profile/profile.component.html
  client/src/app/general/friend-sidebar/profile/profile.component.scss
  client/src/app/pages/home/home.component.html
  client/src/app/pages/home/home.component.scss
  client/src/app/styles/_colors.scss
Labels: enhancement
